import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QRCodeSVG } from 'qrcode.react';
import { Html5QrcodeScanner } from 'html5-qrcode';
import './styles.css';
import './staff.css';
import './pages.css';
import './finance.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const call = async (path, { token, ...options } = {}) => { const r = await fetch(`${API}${path}`, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = r.headers.get('content-type')?.includes('text/csv') ? await r.text() : await r.json(); if (!r.ok) { if (r.status === 401 && token) { localStorage.removeItem('aarohan-session'); window.location.hash = 'login'; } throw Error(data.message || 'Request failed'); } return data; };

function PublicRegistration({ events, refresh, lockedEventId = '' }) {
  const [eventId, setEventId] = useState(lockedEventId || ''); const [notice, setNotice] = useState(''); const [proof, setProof] = useState(null); const [data, setData] = useState({ leader: { name: '', email: '', phone: '' }, college: '', department: '', year: '', teamName: '', members: [], payment: { amount: '', utr: '', screenshotUrl: '' } });
  const event = events.find((x) => x._id === eventId);
  useEffect(() => { if (lockedEventId) setEventId(lockedEventId); }, [lockedEventId]);
  useEffect(() => { if (event) setData((x) => ({ ...x, payment: { ...x.payment, amount: event.fee } })); }, [eventId]);
  const submit = async (e) => { e.preventDefault(); try { setNotice('Submitting…'); let screenshotUrl = data.payment.screenshotUrl; let screenshotFileId = ''; if (proof) { const body = new FormData(); body.append('proof', proof); const uploaded = await call('/uploads/payment-proof', { method: 'POST', body }); screenshotUrl = uploaded.url; screenshotFileId = uploaded.fileId; } const isTeam = String(event?.format || '').toUpperCase() === 'TEAM'; const result = await call('/registrations', { method: 'POST', body: JSON.stringify({ ...data, event: eventId, teamName: isTeam ? data.teamName : '', members: isTeam ? data.members : [], payment: { ...data.payment, amount: event.fee, screenshotUrl, screenshotFileId } }) }); setNotice(`Success — your registration ID is ${result.registrationId}. Payment is pending verification.`); } catch (error) { setNotice(error.message); } };
  const leader = (field) => ({ value: data.leader[field], onChange: (e) => setData({ ...data, leader: { ...data.leader, [field]: e.target.value } }) });
  const customFields = event?.formFields?.filter((field) => /[a-z0-9]/i.test(field.label || '')).map((field) => <label key={field.key}>{field.label}<input required={field.required} value={data.responses?.[field.key] || ''} onChange={(e) => setData({ ...data, responses: { ...(data.responses || {}), [field.key]: e.target.value } })} /></label>);
  const paymentInfo = event && <>{event.upiQrUrl && <img className="upi-qr" src={event.upiQrUrl} alt="UPI payment QR" />}{event.paymentInstructions && <p className="payment-note">{event.paymentInstructions}</p>}{event.upiId && <p className="payment-note">UPI ID: <b>{event.upiId}</b></p>}</>;
  return <section className="layout"><form onSubmit={submit}><h2>{event ? `${event.name} registration` : 'Event registration'}</h2>{!lockedEventId && <label>Choose event<select value={eventId} onChange={(e) => setEventId(e.target.value)} required><option value="">Select an event</option>{events.map((x) => <option key={x._id} value={x._id}>{x.name} — {money.format(x.fee)}</option>)}</select></label>}{lockedEventId && !event && <p className="message">This event registration link is unavailable or no longer active.</p>}{event && <div className="event-note"><b>{event.category}</b> · <b>{event.format}</b> · {event.capacity} seats · Registration fee: {money.format(event.fee)}<br />{event.venue && `Venue: ${event.venue}. `}{event.rules || 'Rules will be announced by the coordinator.'}</div>}<div className="grid"><label>Participant name<input required placeholder="Your full name" {...leader('name')} /></label><label>Mobile number<input required placeholder="10-digit mobile number" {...leader('phone')} /></label></div><label>Email address<input type="email" required placeholder="you@example.com" {...leader('email')} /></label><div className="grid"><label>College name<input required placeholder="Your college" value={data.college} onChange={(e) => setData({ ...data, college: e.target.value })} /></label><label>Year / Department<input placeholder="Example: FY BCA" value={`${data.year}${data.year && data.department ? ' / ' : ''}${data.department}`} onChange={(e) => setData({ ...data, year: e.target.value })} /></label></div>{customFields}<hr /><h3>Payment proof</h3>{paymentInfo}<p className="payment-note">Pay exactly <b>{event ? money.format(event.fee) : 'the event fee'}</b>. This amount is fixed by the event admin.</p><label>UPI transaction ID / UTR<input required placeholder="Enter the UTR after payment" value={data.payment.utr} onChange={(e) => setData({ ...data, payment: { ...data.payment, utr: e.target.value } })} /></label><label>Payment screenshot (JPG, PNG, WebP; maximum 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setProof(e.target.files[0])} /></label><button disabled={!event}>Submit registration</button>{notice && <p className="message">{notice}</p>}</form><Info /></section>;
}
function Info() { return <aside><h2>How it works</h2><ol><li>Register and upload your UPI payment proof.</li><li>Finance verifies the transaction.</li><li>Download your secure QR pass.</li><li>Scan it once at the gate.</li></ol><p className="aside-foot">Bring an active QR pass and college ID.</p></aside>; }
const sponsors = [
  ['Bisleri', '01_Bisleri_HD.jpg'], ['OPPO', '02_OPPO_HD.jpg'], ['RiteBite Max Protein', '03_RiteBite_Max_Protein_HD.jpg'], ['KTM', '04_KTM_HD.jpg'], ['Indian Bank', '05_Indian_Bank_HD.jpg'], ['92.7 Big FM', '06_92_7_Big_FM_HD.jpg'], ['Lakmé', '07_Lakme_HD.jpg'], ['IDFC First Bank', '08_IDFC_First_Bank_HD.jpg'], ['Elegant Marine Services', '09_Elegant_Marine_Services_HD.jpg'], ['Fleet Management Limited', '10_Fleet_Management_Limited_HD.jpg'], ['SAO Foods', '11_SAO_Foods_HD.jpg'], ['SUPCON', '12_SUPCON_HD.jpg'], ['Sports Reconnect', '13_Sports_Reconnect_HD.jpg'], ['Kamala Built on Principles', '14_Kamala_Built_on_Principles_HD.jpg'], ['Total Sports Fitness', '15_Total_Sports_Fitness_HD.jpg'],
];
function Home({ events, go }) { return <><section className="home-hero"><p className="eyebrow">25 YEARS OF LEGACY · ELEVATE · INNOVATE · INSPIRE</p><h1 className="aarohan-title">Abstract Aarohan</h1><h2>The ascent continues</h2><p>Where management, sport, and culture converge under one constellation.</p><div><button onClick={() => go('events')}>Explore events</button><button className="ghost" onClick={() => go('register')}>Register now</button></div></section><section className="sponsors-section"><p className="eyebrow">OUR SPONSORS</p><h2>Powered by our partners</h2><div className="sponsor-marquee" aria-label="Aarohan sponsors"><div className="sponsor-track">{[...sponsors, ...sponsors].map(([name, file], index) => <div className="sponsor-logo" key={`${file}-${index}`} aria-hidden={index >= sponsors.length}><img src={`/sponsors/${file}`} alt={name} /></div>)}</div></div></section><section className="home-section compact"><h2>{events.length ? `${events.length} events are open` : 'Events are launching soon'}</h2><button onClick={() => go('events')}>View event catalogue</button></section></>; }
function EventExplorer({ events, go }) { const categories = [['SPORT', 'Sports'], ['MANAGEMENT', 'Management'], ['CULTURAL', 'Cultural']]; return <section className="catalogue"><p className="eyebrow">EVENT CATALOGUE</p><h1>Choose your challenge</h1>{categories.map(([key, title]) => { const categoryEvents = events.filter((event) => event.category === key); return <section className="category-section" key={key}><p className="eyebrow">{title.toUpperCase()}</p><h2>{title} events</h2>{categoryEvents.length ? <div className="event-grid">{categoryEvents.map((event) => <article key={event._id}><p>{event.format} · {event.venue || 'Venue TBA'}</p><h3>{event.name}</h3><span>{money.format(event.fee)}</span><span>{event.capacity} slots</span><p>{event.rules || 'Details will be published shortly.'}</p><button onClick={() => go(`register/${event._id}`)}>Register</button></article>)}</div> : <p className="empty-category">No {title.toLowerCase()} events are open yet.</p>}</section>; })}{!events.length && <p>No active events yet. The admin will publish them here.</p>}</section>; }

function Login({ onLogin }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); return <section className="auth"><form onSubmit={async (e) => { e.preventDefault(); try { onLogin(await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) })); } catch (x) { setError(x.message); } }}><h2>Staff sign in</h2><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button>Sign in</button>{error && <p className="message">{error}</p>}</form></section>; }
function PassLookup() { const [registrationId, setRegistrationId] = useState(''); const [email, setEmail] = useState(''); const [pass, setPass] = useState(null); const [notice, setNotice] = useState(''); return <section className="auth"><form onSubmit={async (e) => { e.preventDefault(); try { setPass(await call('/registrations/pass-lookup', { method: 'POST', body: JSON.stringify({ registrationId, email }) })); setNotice(''); } catch (x) { setNotice(x.message); } }}><h2>Get your QR pass</h2>{pass ? <div className="ticket"><QRCodeSVG value={`AAROHAN:${pass.token}`} size={220} /><h3>{pass.event}</h3><b>{pass.participant}</b><p>{pass.registrationId}</p><p>{pass.venue || 'Venue to be announced'}</p><button type="button" onClick={() => window.print()}>Print / Save pass</button></div> : <><label>Registration ID<input value={registrationId} onChange={(e) => setRegistrationId(e.target.value)} required /></label><label>Registration email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><button>Find pass</button></>}{notice && <p className="message">{notice}</p>}</form></section>; }

function Staff({ session, events, refresh }) { const [records, setRecords] = useState([]); const [notice, setNotice] = useState(''); const [tab, setTab] = useState('overview'); const load = () => call('/registrations', { token: session.token }).then(setRecords).catch((e) => setNotice(e.message)); useEffect(() => { load(); }, [tab]); const act = async (path, body, method = 'PATCH') => { try { await call(path, { token: session.token, method, body: JSON.stringify(body) }); setNotice('Saved.'); load(); } catch (e) { setNotice(e.message); } }; return <section className="staff"><div className="tabs">{['overview','events', 'staff', 'finance', 'cct', 'gate', 'judge', 'leaderboard'].filter((x) => x === 'overview' || session.user.role === 'SUPER_ADMIN' || x === session.user.role.toLowerCase() || x === 'leaderboard').map((x) => <button className={tab === x ? 'active' : ''} key={x} onClick={() => setTab(x)}>{x}</button>)}</div>{notice && <p className="message">{notice}</p>}{tab === 'overview' && <Overview events={events} records={records} role={session.user.role} />}{tab === 'events' && <EventAdmin token={session.token} events={events} refresh={refresh} setNotice={setNotice} />}{tab === 'staff' && <><StaffAdmin token={session.token} events={events} setNotice={setNotice} /><StaffAssignments token={session.token} events={events} setNotice={setNotice} /></>}{tab === 'finance' && <Finance records={records} act={act} />}{tab === 'cct' && <Roster records={records} events={events} token={session.token} />}{tab === 'gate' && <Gate token={session.token} setNotice={setNotice} />}{tab === 'judge' && <Judge records={records} act={act} />}{tab === 'leaderboard' && <Leaderboard events={events} />}</section>; }
function Overview({ events, records, role }) { const approved = records.filter((x) => x.payment?.status === 'APPROVED').length; const checkedIn = records.filter((x) => x.status === 'CHECKED_IN').length; return <div><p className="eyebrow">{role} COMMAND CENTRE</p><h2>Festival overview</h2><div className="metric-grid"><article><b>{events.length}</b><span>Active events</span></article><article><b>{records.length}</b><span>Registrations</span></article><article><b>{approved}</b><span>Approved payments</span></article><article><b>{checkedIn}</b><span>Checked in</span></article></div><div className="event-note">Use the tabs above to manage the work assigned to your role. All changes are recorded in the audit log.</div></div>; }
function EventAdmin({ token, events, refresh, setNotice }) {
  const [data, setData] = useState({ name:'', category:'SPORT', fee:'', capacity:'', format:'SOLO', minTeamSize:'', maxTeamSize:'', rules:'', venue:'', startsAt:'', upiId:'', paymentInstructions:'', formFields:[] }); const [fields, setFields] = useState(''); const [qr, setQr] = useState(null);
  const input = (key, type='text') => key === 'category'
    ? <label>Event category<select value={data.category} onChange={(e) => setData({ ...data, category:e.target.value })}><option value="SPORT">Sport</option><option value="MANAGEMENT">Management</option><option value="CULTURAL">Cultural</option></select></label>
    : key === 'format'
    ? <label>format<select value={data.format} onChange={(e) => setData({ ...data, format:e.target.value })}><option value="SOLO">SOLO</option><option value="TEAM">TEAM</option></select></label>
    : <label>{key}<input required={['name','fee','capacity'].includes(key)} min={type === 'number' ? 0 : undefined} type={type} value={data[key]} onChange={(e) => setData({ ...data, [key]: e.target.value })} /></label>;
  const submit = async (e) => { e.preventDefault(); try { let upiQrUrl = ''; if (qr) { const fd = new FormData(); fd.append('qr', qr); upiQrUrl = (await call('/uploads/upi-qr', { token, method:'POST', body:fd })).url; } const formFields = fields.split(',').map((label) => label.trim()).filter(Boolean).map((label) => ({ label, key: label.toLowerCase().replace(/[^a-z0-9]+/g, '_'), type:'TEXT', required:true })); const numeric = ['fee','capacity','minTeamSize','maxTeamSize']; const payload = Object.fromEntries(Object.entries(data).map(([key, value]) => [key, numeric.includes(key) && value !== '' ? Number(value) : value])); await call('/events', { token, method:'POST', body:JSON.stringify({ ...payload, upiQrUrl, formFields }) }); setNotice('Event and registration form created.'); refresh(); } catch (x) { setNotice(x.message); } };
  return <div><h2>Event form generator</h2><form onSubmit={submit}><div className="grid">{input('name')}{input('category')}{input('fee','number')}{input('capacity','number')}{input('format')}{input('minTeamSize','number')}{input('maxTeamSize','number')}{input('venue')}{input('startsAt','datetime-local')}{input('upiId')}</div><label>Rules<textarea value={data.rules} onChange={(e) => setData({ ...data, rules:e.target.value })} /></label><label>Payment instructions<textarea placeholder="Example: Pay exact amount to UPI ID, then enter UTR." value={data.paymentInstructions} onChange={(e) => setData({ ...data, paymentInstructions:e.target.value })} /></label><label>UPI QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setQr(e.target.files[0])} /></label><label>Extra registration fields (comma separated)<input placeholder="Example: Branch, T-shirt size, Instagram handle" value={fields} onChange={(e) => setFields(e.target.value)} /></label><button>Create event and form</button></form><Table rows={events} cols={['name','category','format','fee','capacity','venue']} /></div>;
}
function StaffAdmin({ token, events, setNotice }) {
  const [users, setUsers] = useState([]);
  const [data, setData] = useState({ name: '', email: '', password: '', role: 'FINANCE' });
  const load = () => call('/auth/users', { token }).then(setUsers).catch((e) => setNotice(e.message));
  useEffect(() => { void load(); }, []);
  const roles = ['SUPER_ADMIN', 'FINANCE', 'CCT', 'GATE', 'JUDGE'];

  return <div>
    <h2>Staff and event permissions</h2>
    <form onSubmit={async (e) => {
      e.preventDefault();
      try {
        // Assign all events to the user by default
        const body = { ...data, assignedEvents: events.map((x) => x._id) };
        await call('/auth/users', { token, method: 'POST', body: JSON.stringify(body) });
        setNotice('Staff account created.');
        load();
      } catch (x) { setNotice(x.message); }
    }}>
      <div className="grid">
        <label>name<input value={data.name} onChange={(e) => setData({ ...data, name: e.target.value })} required /></label>
        <label>email<input type="email" value={data.email} onChange={(e) => setData({ ...data, email: e.target.value })} required /></label>
        <label>password<input type="password" value={data.password} onChange={(e) => setData({ ...data, password: e.target.value })} required /></label>
        <label>role
          <select value={data.role} onChange={(e) => setData({ ...data, role: e.target.value })}>
            {roles.map((r) => <option key={r} value={r}>{r}</option>)}
          </select>
        </label>
      </div>

      <button>Create staff account</button>
    </form>
    <Table rows={users} cols={['name', 'email', 'role']} />
  </div>;
}
function PaymentProof({ url }) { return url ? <a className="proof-link" href={url} target="_blank" rel="noreferrer">View screenshot</a> : <span className="no-proof">No screenshot</span>; }
function Finance({ records, act }) { return <div><h2>Payment verification</h2><h3>Pending review</h3><Table rows={records.filter((x) => x.payment.status === 'PENDING')} cols={['registrationId', 'event.name', 'leader.name', 'payment.amount', 'payment.utr']} actions={(x) => <><PaymentProof url={x.payment.screenshotUrl} /><button onClick={() => act(`/registrations/${x._id}/payment`, { status: 'APPROVED' })}>Approve</button><button className="danger" onClick={() => act(`/registrations/${x._id}/payment`, { status: 'REJECTED', note: 'Proof needs correction' })}>Reject</button></>} /><h3>Approved passes</h3><Table rows={records.filter((x) => x.payment.status === 'APPROVED')} cols={['registrationId', 'event.name', 'leader.name', 'leader.email']} actions={(x) => <><PaymentProof url={x.payment.screenshotUrl} /><button onClick={() => act(`/registrations/${x._id}/resend-pass`, {}, 'POST')}>Resend QR pass</button></>} /></div>; }
function StaffAssignments({ token, events, setNotice }) { const [users, setUsers] = useState([]); const [userId, setUserId] = useState(''); const [assignedEvents, setAssignedEvents] = useState([]); const load = () => call('/auth/users', { token }).then(setUsers).catch((e) => setNotice(e.message)); useEffect(() => { void load(); }, []); const choose = (id) => { setUserId(id); const user = users.find((item) => item._id === id); setAssignedEvents(user?.assignedEvents?.map((event) => event._id) || []); }; const assignAll = async () => { try { await call('/auth/users/assign-all-events', { token, method:'POST', body:JSON.stringify({}) }); setNotice('All existing staff now have access to every active event.'); load(); } catch (error) { setNotice(error.message); } }; return <section className="assignment-card"><h2>Event access</h2><p>Every staff account is automatically assigned to every active event.</p><button onClick={assignAll}>Assign all events to existing staff</button><details><summary>Optional individual override</summary><label>Staff account<select value={userId} onChange={(e) => choose(e.target.value)}><option value="">Choose staff account</option>{users.filter((user) => user.role !== 'SUPER_ADMIN').map((user) => <option value={user._id} key={user._id}>{user.name} — {user.role}</option>)}</select></label><label>Allowed events<select multiple value={assignedEvents} onChange={(e) => setAssignedEvents([...e.target.selectedOptions].map((option) => option.value))}>{events.map((event) => <option value={event._id} key={event._id}>{event.name}</option>)}</select></label><button disabled={!userId} onClick={async () => { try { await call(`/auth/users/${userId}`, { token, method:'PATCH', body:JSON.stringify({ assignedEvents }) }); setNotice('Event permissions updated.'); load(); } catch (error) { setNotice(error.message); } }}>Save individual override</button></details></section>; }
function Roster({ records, events, token }) {
  const [category, setCategory] = useState(''); const [eventId, setEventId] = useState('');
  const categoryEvents = events.filter((item) => !category || item.category === category);
  const roster = records.filter((record) => record.event?._id === eventId);
  const event = events.find((item) => item._id === eventId);
  const download = async () => {
    if (!eventId) return;
    const response = await fetch(`${API}/registrations/export/event/${eventId}`, { headers: { Authorization: `Bearer ${token}` } });
    if (!response.ok) { alert('Could not export this roster. Please try again.'); return; }
    const blob = await response.blob(); const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: `${event?.name || 'event'}-roster.csv` }); a.click(); URL.revokeObjectURL(a.href);
  };
  const downloadCategory = async () => { if (!category) return; const response = await fetch(`${API}/registrations/export/category/${category}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { alert('Could not export this category.'); return; } const blob = await response.blob(); const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: `${category.toLowerCase()}-category-roster.csv` }); a.click(); URL.revokeObjectURL(a.href); };
  const downloadWorkbook = async () => { const response = await fetch(`${API}/registrations/export/categories-workbook`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { alert('Could not create the category workbook. Please try again.'); return; } const blob = await response.blob(); const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'abstract-aarohan-category-rosters.xlsx' }); a.click(); URL.revokeObjectURL(a.href); };
  return <div><p className="eyebrow">CCT EVENT MANAGEMENT</p><h2>Category and event-wise roster</h2><button onClick={downloadWorkbook}>Download all categories Excel workbook</button><p className="event-note">The workbook contains separate Sports, Management, and Cultural tabs.</p><div className="grid"><label>1. Choose category<select value={category} onChange={(e) => { setCategory(e.target.value); setEventId(''); }}><option value="">All categories</option><option value="SPORT">Sport</option><option value="MANAGEMENT">Management</option><option value="CULTURAL">Cultural</option></select></label><label>2. Choose event<select value={eventId} onChange={(e) => setEventId(e.target.value)}><option value="">Select an event</option>{categoryEvents.map((item) => <option key={item._id} value={item._id}>{item.name} ({item.category})</option>)}</select></label></div>{category && <button onClick={downloadCategory}>Download all {category.toLowerCase()} participants CSV</button>}{eventId && <><div className="metric-grid"><article><b>{roster.length}</b><span>Total registrations</span></article><article><b>{roster.filter((item) => item.payment?.status === 'APPROVED').length}</b><span>Approved</span></article><article><b>{roster.filter((item) => item.status === 'CHECKED_IN').length}</b><span>Checked in</span></article><article><b>{event?.capacity || '—'}</b><span>Capacity</span></article></div><button onClick={download}>Download {event?.name} CSV</button><Table rows={roster} cols={['registrationId', 'leader.name', 'leader.email', 'leader.phone', 'teamName', 'payment.amount', 'payment.status', 'status']} /></>}{!eventId && <div className="event-note">Choose a category to download every participant in that category, or choose an event for its individual roster.</div>}</div>;
}
function AdminManage({ session, events, refresh }) {
  const [staff, setStaff] = useState([]); const [participants, setParticipants] = useState([]); const [notice, setNotice] = useState('');
  const load = () => Promise.all([call('/auth/users', { token: session.token }), call('/registrations', { token: session.token })]).then(([users, registrations]) => { setStaff(users); setParticipants(registrations); }).catch((error) => setNotice(error.message));
  useEffect(() => { void load(); }, []);
  const remove = async (path, label) => { if (!window.confirm(`Delete ${label}? This cannot be undone.`)) return; try { const result = await call(path, { token: session.token, method: 'DELETE' }); setNotice(result.message || 'Deleted.'); await refresh(); load(); } catch (error) { setNotice(error.message); } };
  return <section className="staff management-page"><p className="eyebrow">SUPER ADMIN ONLY</p><h2>Delete management</h2><p className="event-note">Delete participant registrations first, then their event. Your own Super Admin account cannot be deleted.</p>{notice && <p className="message">{notice}</p>}<h3>Events</h3><Table rows={events} cols={['name', 'category', 'format', 'fee', 'capacity']} actions={(event) => <button className="danger" onClick={() => remove(`/events/${event._id}`, `the event “${event.name}”`)}>Delete event</button>} /><h3>Staff accounts</h3><Table rows={staff} cols={['name', 'email', 'role']} actions={(user) => <button className="danger" disabled={user._id === session.user.id} onClick={() => remove(`/auth/users/${user._id}`, `the staff account for ${user.name}`)}>Delete staff</button>} /><h3>Participants</h3><Table rows={participants} cols={['registrationId', 'leader.name', 'leader.email', 'event.name', 'payment.status', 'status']} actions={(participant) => <button className="danger" onClick={() => remove(`/registrations/${participant._id}`, `registration ${participant.registrationId}`)}>Delete participant</button>} /></section>;
}
function Gate({ token, setNotice }) { const [value, setValue] = useState(''); const validate = async (tokenValue) => { try { const r = await call('/registrations/scan', { token, method: 'POST', body: JSON.stringify({ token: tokenValue }) }); setNotice(`${r.message}: ${r.participant}`); setValue(''); } catch (e) { setNotice(e.message); } }; useEffect(() => { const scanner = new Html5QrcodeScanner('qr-reader', { fps: 10, qrbox: 240 }, false); scanner.render((decoded) => { void scanner.clear(); void validate(decoded); }, () => {}); return () => { void scanner.clear().catch(() => {}); }; }, []); return <div className="scanner"><h2>Gate check-in</h2><div id="qr-reader"></div><p>Camera scan or paste the QR value below.</p><input placeholder="Paste QR token" value={value} onChange={(e) => setValue(e.target.value)} /><button onClick={() => validate(value)}>Validate pass</button></div>; }
function Judge({ records, act }) { return <div><h2>Scoring</h2><Table rows={records.filter((x) => ['CHECKED_IN', 'VERIFIED'].includes(x.status))} cols={['registrationId', 'event.name', 'leader.name', 'score', 'penalty', 'status']} actions={(x) => <><button onClick={() => act(`/registrations/${x._id}/score`, { score: Number(prompt('Score', x.score)), penalty: Number(prompt('Penalty', x.penalty)) })}>Score</button>{x.status === 'VERIFIED' && <button onClick={() => act(`/registrations/${x._id}/finalize`, { rank: Number(prompt('Rank (1, 2, 3…)')) }, 'POST')}>Finalize</button>}</>} /></div>; }
function Leaderboard({ events }) { const [eventId, setEventId] = useState(''); const [rows, setRows] = useState([]); return <div><h2>Public leaderboard</h2><select value={eventId} onChange={async (e) => { setEventId(e.target.value); setRows(e.target.value ? await call(`/registrations/leaderboard/${e.target.value}`) : []); }}><option value="">Choose event</option>{events.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select><Table rows={rows} cols={['rank', 'teamName', 'leader.name', 'score', 'penalty']} /></div>; }
function Table({ rows, cols, actions }) { const get = (item, path) => path.split('.').reduce((v, key) => v?.[key], item) ?? '—'; return <div className="table-wrap"><table><thead><tr>{cols.map((x) => <th key={x}>{x.replace('.', ' ')}</th>)}{actions && <th>Actions</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row._id || row.registrationId}>{cols.map((x) => <td key={x}>{get(row, x)}</td>)}{actions && <td className="actions">{actions(row)}</td>}</tr>)}{!rows.length && <tr><td colSpan={cols.length + 1}>No records.</td></tr>}</tbody></table></div>; }

function App() { const [events, setEvents] = useState([]); const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('aarohan-session') || 'null'); } catch { localStorage.removeItem('aarohan-session'); return null; } }); const [page, setPage] = useState(() => location.hash.slice(1) || 'home'); const refresh = () => call('/events').then(setEvents).catch(() => {}); useEffect(() => { void refresh(); }, []); useEffect(() => { const syncPage = () => { setPage(location.hash.slice(1) || 'home'); if (location.hash === '#login') setSession(null); }; window.addEventListener('hashchange', syncPage); return () => window.removeEventListener('hashchange', syncPage); }, []); const go = (target) => { setPage(target); location.hash = target; window.scrollTo(0, 0); }; const login = (s) => { localStorage.setItem('aarohan-session', JSON.stringify(s)); setSession(s); go('staff'); }; const publicNavigation = !session || session.user.role === 'SUPER_ADMIN'; const isRegistrationPage = page === 'register' || page.startsWith('register/'); const lockedEventId = page.startsWith('register/') ? page.split('/')[1] : ''; return <main><nav><div className="brand"><img src="/college-logo.jpg" alt="Fr. C. Rodrigues Institute of Management Studies emblem" /><strong className="aarohan-wordmark">ABSTRACT AAROHAN</strong></div><div>{publicNavigation && <><button onClick={() => go('home')}>Home</button><button onClick={() => go('events')}>Events</button><button onClick={() => go('register')}>Register</button><button onClick={() => go('pass')}>My pass</button></>}{session?.user.role === 'SUPER_ADMIN' && <button onClick={() => go('manage')}>Manage</button>}<button onClick={() => go(session ? 'staff' : 'login')}>{session ? session.user.role : 'Staff sign in'}</button>{session && <button onClick={() => { localStorage.removeItem('aarohan-session'); setSession(null); go('home'); }}>Sign out</button>}</div></nav>{page === 'home' && <Home events={events} go={go} />}{page === 'events' && <EventExplorer events={events} go={go} />}{isRegistrationPage && <><section className="hero"><p className="eyebrow">REGISTER · COMPETE · WIN</p><h1>Your stage is waiting.</h1><p>Register now. Your QR entry pass follows finance approval.</p></section><PublicRegistration events={events} refresh={refresh} lockedEventId={lockedEventId} /></>}{page === 'pass' && <PassLookup />}{page === 'login' && <Login onLogin={login} />}{page === 'staff' && session && <Staff session={session} events={events} refresh={refresh} />}{page === 'manage' && session?.user.role === 'SUPER_ADMIN' && <AdminManage session={session} events={events} refresh={refresh} />}{page === 'staff' && !session && <Login onLogin={login} />}</main>; }
class AppErrorBoundary extends React.Component { constructor(props) { super(props); this.state = { error: false }; } static getDerivedStateFromError() { return { error: true }; } componentDidCatch(error) { console.error('Aarohan UI error:', error); if (!sessionStorage.getItem('aarohan-auto-reloaded')) { sessionStorage.setItem('aarohan-auto-reloaded', 'true'); window.location.reload(); } } render() { return this.state.error ? <main className="recovery"><h1>Unable to load this view</h1><p>Please try again.</p><button onClick={() => { sessionStorage.removeItem('aarohan-auto-reloaded'); window.location.reload(); }}>Try again</button></main> : this.props.children; } }
createRoot(document.getElementById('root')).render(<AppErrorBoundary><App /></AppErrorBoundary>);
