export const ROLES = ['SUPER_ADMIN', 'FINANCE', 'CCT', 'GATE', 'JUDGE'];
export const PAYMENT_STATUS = ['PENDING', 'APPROVED', 'REJECTED'];
export const REGISTRATION_STATUS = ['PENDING', 'APPROVED', 'CHECKED_IN', 'VERIFIED', 'FINALIZED', 'DISQUALIFIED'];
